services:
  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - JAVA_OPTS=-Xmx512m -Xms256m
    networks:
      - spring-network
    depends_on:
      - postgres
      - redis
  postgres:
    image: postgres:17.2
    environment:
    - POSTGRES_DB=carbon-shop
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=P4ssword!
    ports:
    - 5432:5432
    volumes:
    - ./postgres-data:/var/lib/postgresql/data
    networks:
    - spring-network
  redis:
    image: redis:latest
    ports:
    - 6379:6379
    networks:
    - spring-network

networks:
  spring-network:
    driver: bridge