services:
  postgres:
    image: postgres:17.2
    environment:
    - POSTGRES_DB=carbon-shop
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=P4ssword!
    ports:
    - 5433:5432
  redis:
    image: redis:latest
    ports:
      - '6379:6379'
